version: "3.8"

services:
  postgres:
      image: postgres:17
      container_name: postgres
      environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
        POSTGRES_DB: postgres
      networks:
        - app-network
      ports:
        - "5432:5432"
      restart: always

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network
    restart: always

  django:
    container_name: django
    build: 
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - app-network
    restart: unless-stopped

  celery:
    container_name: celery
    build: .
    command: celery -A project_0 worker -l INFO -B
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
      - django
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
