version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network
    restart: always

  django:
    container_name: django
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    restart: unless-stopped

  celery:
    container_name: celery
    build: .
    command: celery --app=project_0 worker --loglevel=INFO
    volumes:
      - .:/app
    depends_on:
      - redis
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
