version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  app:
    build: .
    container_name: celery-app
    command: poetry run celery -A celery_app worker --loglevel=info
    depends_on:
      - redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge