# Generated by Django 5.1.5 on 2025-05-18 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('difference_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='transactions.transaction')),
                ('income', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfer', to='transactions.transaction')),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcoming_transfer', to='transactions.transaction')),
            ],
        ),
    ]
