# Generated by Django 5.1.4 on 2025-01-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_id', models.CharField(max_length=255)),
                ('unix_time', models.IntegerField()),
                ('mcc', models.IntegerField()),
                ('original_mcc', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('original_amount', models.IntegerField()),
                ('currency_code', models.IntegerField()),
                ('commission_rate', models.IntegerField()),
                ('balance', models.IntegerField()),
            ],
        ),
    ]
