# Generated by Django 5.1.5 on 2025-03-07 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_alter_transaction_options_alter_transaction_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='bank_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
