# Generated by Django 5.1.5 on 2025-03-09 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0003_alter_transaction_bank_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='original_mcc',
        ),
    ]
