# Generated by Django 5.1.5 on 2025-03-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0004_remove_transaction_original_mcc'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatementFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('proccessed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'statement_files',
            },
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={},
        ),
    ]
