# Generated by Django 5.1.5 on 2025-03-10 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0005_statementfile_alter_transaction_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='original_amount',
            new_name='operation_amount',
        ),
    ]
